version: '3.6'

services:
  nginx:
    image: nginx:bbr
    container_name: sf4nginx
    ports:
      - "80:80"
    volumes:
      - ../web/:/var/www/html/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default

  php:
    image: php_fpm:bbr
    container_name: sf4php
    ports:
      - "9000:9000"
    volumes:
      - ../web/:/var/www/html/
      - ./zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    networks:
      - default

networks:
  default:
    external:
      name: humle_net
