version: '3.3'

services:
  nginx:
    image: nginx:bbr
    container_name: sf4nginx
    ports:
      - "80:80"
    volumes:
      - phpsocket:/run/php/
      - ../web/:/var/www/html/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default

  php:
    image: php_fpm:bbr
    container_name: sf4php
    volumes:
      - phpsocket:/run/php/
      - ../web/:/var/www/html/
      - ./zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    networks:
      - default

volumes:
  phpsocket:
    external: true

networks:
  default:
    external:
      name: humle_net
