version: '3.3'
# NB det er kun src/index.html filen, der kan vises da php-fpm ikke er implementeret
services:
  apache:
    image: httpd:bbr
    container_name: sf4apache
    ports:
      - "80:80"
    volumes:
      - phpsocket:/run/php/
      - ../../web/:/var/www/html/
      - ./default.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    networks:
      - default

  php:
    image: php_fpm:bbr
    container_name: sf4php
    volumes:
      - phpsocket:/run/php/
      - ../../web/:/var/www/html/
      - ./zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    networks:
      - default

volumes:
  phpsocket:
    external: true

networks:
  default:
    external:
      name: humle_net
